---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: adoptopenjdk/openjdk15:alpine-slim
    commands:
      - ./mvnw install -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - ./mvnw test -B

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - target
    volumes:
      - name: cache
        path: /cache  


  - name: prepare-cache
    image: busybox
    commands:
      - mkdir -p /cache/bruinkool/target
      - mkdir -p /cache/bruinkool/docker
    volumes:
      - name: cache
        path: /cache


  - name: docker
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      password:
        from_secret: REGISTRY_PASSWORD
      registry: harbor.gate.sh
      repo: harbor.gate.sh/bruinkool/garzweiler
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_COMMIT_BRANCH}
      force_tag: true
      use_cache: true
      username:
        from_secret: REGISTRY_USERNAME
    volumes:
      - name: docker
        path: /var/lib/docker
    when:
      event:
        - push

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - target
    volumes:
      - name: cache
        path: /cache

  - name: deploy
    image: harbor.gate.sh/mdeheij/kubernetes-helm-deploy
    commands:
      - echo "$HELM_VALUES" | base64 -d > .helm_values.yaml
      - sed "s|%%APP_VERSION%%|${DRONE_COMMIT_SHA:0:7}|g" -i .helm_values.yaml
      - drone-helm3
    environment:
      HELM_VALUES:
        from_secret: HELM_VALUES
    settings:
      kube_api_server: { from_secret: KUBERNETES_SERVER }
      kube_token: { from_secret: KUBE_TOKEN }
      kube_certificate: { from_secret: KUBE_CERTIFICATE }
      chart: ./charts/garzweiler
      release: garzweiler
      debug: false
      helm_debug: true
      namespace: bruinkool
      timeout: 2m
      envsubst: true
      values_yaml: [".helm_values.yaml"]
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: target
    host:
      path: /var/cache/bruinkool/target
  - name: docker
    host:
      path: /var/cache/bruinkool/docker
